apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cvdfg-dotnet-app-
spec:
  params:
    - name: GIT_URL
      value: 'sdfdsfds'
    - name: REGISTRY
      value: "sdfsdf"
    - name: IMAGE_NAME
      value: dotnet-app
    - name: IMAGE_TAG
      value: v8
  pipelineRef:
    name: __USER#__-dotnet-app
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: storage
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Mi
          volumeMode: Filesystem
