apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: user#-dotnet-app-
spec:
  params:
    - name: GIT_URL
      value: "___GIT-REPO___"
    - name: REGISTRY
      value: tal-hason
    - name: IMAGE_NAME
      value: dotnet-app
    - name: IMAGE_TAG
      value: v10
    - value: user#-application
  pipelineRef:
    name: user#-dotnet-app
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: storage
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 150Mi
          volumeMode: Filesystem
